#!/bin/sh -x

set -e

ROOT=`readlink -m $(dirname $0)`

ROOT=$(pwd)

test -d $ROOT/.git || (echo "Must be launched in GIT repo root"; exit 1)

DIST=$ROOT/.dist

COMMIT=$(git rev-parse HEAD)
COMMIT_DESCRIPTION=$(git describe || git rev-parse HEAD)

REPO=single-commit-$COMMIT_DESCRIPTION

COMMIT_MSG_FILE=$DIST/COMMIT_MSG-$COMMIT_DESCRIPTION

AUTHOR="$(git config mkdist.name || echo 'gitmkdist') <$(git config mkdist.email || echo 'gitmkdist@localhost')>"


[ "$(git config mkdist.keep-dists)" != "true" ] && rm -Rf $DIST

mkdir -p $DIST

cd $DIST

rm -Rf $REPO
git clone --no-hardlinks --progress --no-checkout $ROOT $REPO

echo "Single commit repo\n\ncommit:$COMMIT\n$COMMIT_DESCRIPTION" > $COMMIT_MSG_FILE

cd $DIST/$REPO
git checkout $COMMIT

# submodules (TODO if exists)
git submodule init
git submodule update

# Some housekeeping
rm -Rf .git
find . -name '.git' -delete
find . -name '.gitmodules' -delete

# Create a brand-new git repo for dist
git init
git add .

# Commit
git commit --quiet --author="$AUTHOR" --file=$COMMIT_MSG_FILE 
